behat.yml, composer.json, composer.lock, package-lock.json, package.json
**Issue URL:** none
1.  Removed `DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension`
=> Removed obsolete extension.

.docker/Dockerfile.cli, composer.json, composer.lock, phpcs.xml
=> Updated PHP to 7.2.

composer.lock, docroot/themes/custom/mysitetheme/scss/_variables.scss, package-lock.json, package.json, tests/bats/artefact.bats, tests/bats/workflow.bats
- Updated dependencies
- Fixed tests
=> Updated dependencies + fixed tests.

.ahoy.yml, .env, install.sh, tests/bats/workflow.bats
=> Added lint and test failing flags + tests.

.ahoy.yml
=> Updated Ahoy config to fail if any commands fail.

.ahoy.yml, .circleci/config.yml, .circleci/process-artifacts.sh, .env, .lagoon.yml, README.md, install.sh, tests/bats/artefact.bats, tests/bats/helpers.bats, tests/bats/install.bats, tests/bats/test_helper.bash, tests/bats/test_helper_drupaldev.bash, tests/bats/workflow.bats
- Added selection of deployments.
- Added selection of dependencies.io integration.
- Removed FTP tests (need to be added separately)
- Removed deployment artifact tests with Acquia integration (will need to be added separately).
- Renamed CI test artifacts handling script.
- Renamed DUMMY_DB to DEMO_DB and added test DB.
- Fixed multiple test assertions.
- Refactored artifact test to not rely on FTP integration.
- Refactored workflow test to not rely on FTP integration.
=> Refactored Acquia, FTP and Dependencies.io into separate deployment steps + tests.

.ahoy.yml, README.md, scripts/doctor.sh, tests/bats/test_helper_drupaldev.bash, tests/bats/workflow0.bats
- Added a pre-flight environment check using existing doctor script.
- Updated documentation to better reflect changes.
=> Added preflight checks and updated docs.

README.md
**Issue URL:**
Closes #427 
Updated Link to pygmy documentation
=> #427 - Fix link to Pygmy Documentation

.ahoy.yml, .circleci/build.sh, .env, .gitignore, .lagoon.yml, composer.json, composer.lock, docker-compose.yml, docroot/modules/custom/your_site_core/tests/src/Unit/YourSiteCoreHelperUnitTest.php, docroot/modules/custom/your_site_core/tests/src/Unit/YourSiteCoreUnitTestCase.php, drush/aliases.drushrc.php, phpunit.xml, scripts/doctor.sh, tests/bats/test_helper_drupaldev.bash, tests/bats/workflow0.bats, tests/bats/workflow1.bats
=> Added support for phpunit tests + preflights checks.

.docker/Dockerfile.cli, .docker/Dockerfile.nginx-drupal, .docker/Dockerfile.php, .docker/Dockerfile.solr, .env, composer.lock, docker-compose.yml
- Updated images to the latest version.
- Updated Drupal core and modules to the latest versions.
=> [7.x] Platform and application updates.

.docker/Dockerfile.cli, .docker/Dockerfile.nginx-drupal, .docker/Dockerfile.php, .docker/Dockerfile.solr, .env, composer.lock, docker-compose.yml
- Updated images to the latest version.
- Updated Drupal core and modules to the latest versions.
=> [8.x] Platform and application updates.

install.sh, tests/bats/clean.bats, tests/bats/install_existing.bats, tests/bats/install_initial.bats, tests/bats/test_helper_drupaldev.bash, tests/bats/workflow0.bats, tests/bats/workflow1.bats
=> [8.x] Fixed camel cased files not being renamed correctly.

.ahoy.yml, .docker/Dockerfile.cli, .docker/scripts/60-php-xdebug.sh, .docker/scripts/61-php-xdebug-cli-env.sh, .dockerignore, FAQs.md, README.md, docker-compose.yml, tests/bats/workflow0.bats
This PR allows to enable xdebug using `ahoy debug` and disable it by `ahoy up`. 🚀
=> [8.x, #498] Added 'ahoy debug' command + tests.

.ahoy.yml, .docker/Dockerfile.cli, .docker/scripts/60-php-xdebug.sh, .docker/scripts/61-php-xdebug-cli-env.sh, .dockerignore, FAQs.md, README.md, docker-compose.yml, tests/bats/workflow0.bats
This PR allows to enable xdebug using `ahoy debug` and disable it by `ahoy up`. 🚀
=> [7.x, #498] Added 'ahoy debug' command + tests.

composer.json, tests/bats/workflow0.bats, tests/bats/workflow1.bats
Until https://github.com/Behat/Gherkin/pull/129 is fixed.
=> Removed support for running single behat tests.

.env, install.sh, tests/bats/_helper_drupaldev.bash, tests/bats/_helper_drupaldev_deployment.bash, tests/bats/install_demo.bats, tests/bats/install_initial.bats, tests/bats/workflow0.bats, tests/bats/workflow1.bats
- Added `DRUPALDEV_DEMO` mode + auto-discovery + tests. This now allows to correctly have demo database dump downloaded on a very first install.
- Updated verbosity of the files copying for better DX.
=> More fixes to enable demo mode.

.circleci/config.yml
=> [#556] Added default timezone for CI runner container.

.ahoy.yml, scripts/drevops/build.sh, scripts/drevops/doctor.sh
- Fixed Doctor's check for bootstrap.
- Added confirmation to 'ahoy build' and 'ahoy down'.
=> Fixed Doctor's check for bootstrap.

docroot/sites/default/settings.php, hooks/common/post-code-update/3.notify-deployment.php, hooks/library/notify-deployment.php, scripts/composer/ScriptHandler.php
- Fixed Acquia ODE env not correctly setting the environment.
- Updated config sync directory in settings.
- Added email notification to Acquia hooks.
=> [8.x] Latest updates and fixes.

.docker/Dockerfile.cli, .docker/Dockerfile.mariadb, .env, scripts/drevops/build.sh, scripts/drevops/drupal-install-site.sh, scripts/drevops/tests/bats/workflow0.bats
- Fixed default DB image value.
- Added FORCE_FRESH_INSTALL flag to fresh install even if the site exis… …
- Added a variable to unblock admin user.
- Fixed composer install running out of memory.
=> [8.x] Multiple updates.

.circleci/config.yml
Fixed DB caching not using correct DB cache for the first build of the non-default branch.
=> [8.x] Fixed DB caching in CI.

.circleci/config.yml, .circleci/drevops-test.sh, .env, install.php, scripts/drevops/deploy-lagoon.sh, scripts/drevops/deploy.sh, scripts/drevops/drupal-install-site.sh, scripts/drevops/tests/bats/_helper_drevops.bash, scripts/drevops/tests/bats/_helper_drevops_deployment.bash, scripts/drevops/tests/bats/_mock.bash, scripts/drevops/tests/bats/deployment1.bats, scripts/drevops/tests/bats/fixture.sh, scripts/drevops/tests/bats/mock.bats
Added new deployment type to Lagoon and added bats tests.
=> Added Laggon deployment type + tests.

.docker/Dockerfile.cli, .docker/Dockerfile.mariadb, .docker/Dockerfile.nginx-drupal, .docker/Dockerfile.php, .docker/Dockerfile.solr, composer.json, docker-compose.yml, scripts/drevops/doctor.sh
- Updated images to v1.10.0
- Updated PHP to 7.4.
- Updated link references in comments.
=> [8.x] Updated images to v1.10.0 and PHP to 7.4.

.ahoy.yml, .docker/Dockerfile.cli, .docker/Dockerfile.mariadb, .docker/Dockerfile.nginx-drupal, .docker/Dockerfile.php, .docker/Dockerfile.solr, .env, .lagoon.yml, FAQs.md, README.md, default.env.local, docroot/modules/custom/your_site_core/drush.services.yml, docroot/modules/custom/your_site_core/src/Commands/PostConfigImportUpdateCommands.php, docroot/modules/custom/your_site_core/src/PostConfigImportUpdateHelper.php, phpcs.xml, scripts/drevops/build.sh, scripts/drevops/drupal-install-site.sh, scripts/drevops/test.sh
**Issue URL:**
-  Added rerunning of failed Behat tests.
- Added enabling and disabling maintenance mode on build.
- Fixed config split not using correct configuration per environment.
- Fixed 'ahoy debug' not restarting nginx service.
- Added post config import update Drush command.
- Removed incorrect Lagoon config value.
- Added default local `.env` file as a template for `.env.local`.
- Added conditional install of theme assets if the theme was provided.
- Added JS and CSS to PHPCS lint target.
- Added additional PHPCS rules to enforce no empty lines before and after functions.
- Added FAQ item about debugging Behat tests.
- Updated comments in Docker files.
=> [8.x] Miscellaneous updates.

.circleci/config.yml, default.env.local, docroot/modules/custom/your_site_core/drush.services.yml, docroot/sites/default/settings.php, install.php, scripts/drevops/tests/bats/install_initial.bats
**Issue URL:**
- Fixed typo in drush services.
- Fixed typo in CI config.
- Added Lagoon cloud routes to trusted host patterns.
- Added `config_exclude_modules` variable to settings.
- Added `CONFIRM_RESPONSE` to default env file.
- Fixed install token replacement in binary files.
=> [8.x] Multiple fixes.

.ahoy.yml, README.md
**What has changed**
1. Nit: Updated test command descriptions from simpletest to PHPUnit.
2. Updated test command to run all tests not just unit & BDD.
=> Update command descriptions and run all tests.

.circleci/config.yml, docroot/modules/custom/your_site_core/your_site_core.install
- Added support for `DATABASE_SSH_FINGERPRINT` in CI.
- Added running of post_update hooks on core module install.
=> Added database fingerprint in CI and running of post_update hooks on core module install.

.circleci/config.yml, scripts/drevops/tests/composer.json, scripts/drevops/tests/composer.lock, scripts/drevops/tests/unit/DrevopsTestCase.php, scripts/drevops/tests/unit/DrevopsTestHelperTrait.php, scripts/drevops/tests/unit/InstallerCopyRecursiveTest.php, scripts/drevops/tests/unit/InstallerDotEnvTest.php, scripts/drevops/tests/unit/InstallerHelpersTest.php, scripts/drevops/tests/unit/InstallerTokenTest.php
=> Updated test fixtures to be compatible with the latest coding standards.

scripts/drevops/deploy-lagoon.sh, scripts/drevops/deploy.sh, scripts/drevops/drupal-install-site.sh, scripts/drevops/tests/bats/deployment1.bats
- Updated Lagoon deployment script to support creating and deleting environments.
- Added skipping of deployments using env variables `DEPLOY_SKIP_PR_<NUMBER>` and `DEPLOY_SKIP_BRANCH_<SAFE_BRANCH>`.
- Updated Drupal install script to be more verbose.
=> Update deployment scripts.

docroot/modules/custom/ys_core/tests/src/Functional/YsCoreExampleFunctionalTest.php, docroot/modules/custom/ys_core/tests/src/Kernel/YsCoreExampleKernelTest.php, docroot/modules/custom/ys_core/tests/src/Unit/YsCoreExampleUnitTest.php, docroot/sites/default/default.settings.php, phpcs.xml, scripts/drevops/tests/bats/_helper.bash, scripts/drevops/tests/bats/_helper_drevops.bash, scripts/drevops/tests/bats/docker-compose.bats, scripts/drevops/tests/bats/fixtures/docker-compose.fixture.yml, scripts/drevops/tests/bats/fixtures/docker-compose.fixture2.yml, scripts/drevops/tests/bats/fixtures/fixture1.txt, scripts/drevops/tests/bats/fixtures/fixture1_newline.txt, scripts/drevops/tests/bats/fixtures/fixture2.txt, scripts/drevops/tests/bats/helpers.bats, scripts/drevops/tests/bats/helpers_drevops.bats, scripts/drevops/tests/bats/install_initial.bats, scripts/drevops/utils/ci-drevops-test.sh
- Fixed tests to be compatible with Bats 1.7
- Added Bats helper to compare text files with skipping space differences
- Added DrevOps helpers + tests.
=> [9.x] Fix CI build.

.github/workflows/auto-assign-pr-author.yml
Closes https://github.com/drevops/drevops/issues/760
=> [#760] Added GitHub action to auto-assign PR author.

scripts/drevops/drupal-install-site.sh, scripts/drevops/tests/bats/drupal_install_site.bats
Closes https://github.com/drevops/drevops/issues/746
=> [#746] Added core version to the site install output.

scripts/drevops/deploy-lagoon.sh, scripts/drevops/docs/variables.md, scripts/drevops/task-custom-lagoon.sh, scripts/drevops/tests/bats/deployment1.bats, scripts/drevops/utils/.aspell.en.pws
Closes https://github.com/drevops/drevops/issues/757
Closes https://github.com/drevops/drevops/issues/758
=> [#757, #758] Added support for custom LagoonCLI version and Lagoon instance.

scripts/drevops/deploy-artifact.sh, scripts/drevops/mirror-code.sh
Closes https://github.com/drevops/drevops/issues/763
=> [#763] Added script to mirror code between branches.

.docker/cli.dockerfile, .docker/php.dockerfile, composer.json, phpcs.xml
closes https://github.com/drevops/drevops/issues/775
closes https://github.com/drevops/drevops/issues/771
=> Updated to PHP 8.1.

install.php
Closes #750
```
╭──────────────────────────────────────────────────────────────────────────────╮
|                      WELCOME TO DREVOPS QUIET INSTALLER                      |
├──────────────────────────────────────────────────────────────────────────────┤
│                                                                              │
│  This will install the latest version of DrevOps into your project.          │
│                                                                              │
│  DrevOps installer will try to discover the settings from the environment    │
│  and will install configuration relevant to your site.                       │
│                                                                              │
│  Existing committed files will be modified. You will …
```
=> [#750] Updated messaging and frames in the installer script.

docroot/modules/custom/ys_core/tests/src/Functional/YsCoreExampleFunctionalTest.php, docroot/modules/custom/ys_core/tests/src/Kernel/YsCoreExampleKernelTest.php, docroot/modules/custom/ys_core/tests/src/Unit/YsCoreExampleUnitTest.php, scripts/drevops/test.sh
=> [#738] Allow to skip unit, functional and kernel tests tagged with skipped group.

.ahoy.yml, scripts/drevops/build.sh, scripts/drevops/deploy.sh, scripts/drevops/docs/variables.md, scripts/drevops/lint.sh, scripts/drevops/test.sh, scripts/drevops/tests/bats/deployment0.bats
=> Multiple fixes.

scripts/drevops/docs/variables.md, scripts/drevops/drupal-install-site.sh
Added `DREVOPS_DRUPAL_INSTALL_SKIP` flag.
=> Added skipping of the site installation.

.docker/cli.dockerfile, .docker/mariadb.dockerfile, .docker/nginx-drupal.dockerfile, .docker/php.dockerfile, .docker/solr.dockerfile, docker-compose.yml, scripts/drevops/tests/bats/fixtures/docker-compose.fixture.yml, scripts/drevops/tests/bats/fixtures/docker-compose.fixture2.yml
=> [#811] Updated Docker images to 23.2.0

scripts/drevops/utils/.aspell.en.pws, scripts/drevops/utils/lint-spelling.sh
=> [#817] Fix spellchecker dictionary.

.docker/cli.dockerfile, .docker/mariadb.dockerfile, .docker/nginx-drupal.dockerfile, .docker/php.dockerfile, .docker/solr.dockerfile, scripts/drevops/tests/.ahoy.yml, scripts/drevops/tests/lint-dockerfiles.sh, scripts/drevops/tests/test.common.sh
=> [#819] Added linting of Dockerfiles.

.circleci/config.yml, .gitattributes, scripts/drevops/installer/install.php, scripts/drevops/tests/bats/_helper.bash, scripts/drevops/tests/bats/update.bats, scripts/drevops/tests/lint-scripts.sh, scripts/drevops/tests/unit/InstallerTestCase.php
=> chore: Move install file away from the root (#824 ).

scripts/drevops/doctor.sh
=> fix: Fixed incorrect doctor status for when pygmy is not running.

.gitignore.deployment, scripts/drevops/tests/bats/_helper.bash, scripts/drevops/tests/bats/_helper_deployment.bash, scripts/drevops/tests/bats/_helper_workflow.bash, scripts/drevops/tests/bats/deployment0.bats, scripts/drevops/tests/bats/deployment1.bats
=> chore: Simplified artifact deployment gitignore config to deploy full code artifact.

scripts/drevops/tests/lint-scripts.sh, scripts/drevops/tests/unit/DrupalSettingsTest.php, web/sites/default/settings.php
=> feat: Added support for release/* and hotifx/* Lagoon envs identification in settings.php 

behat.yml, docker-compose.yml, scripts/drevops/tests/bats/fixtures/docker-compose.fixture.yml, scripts/drevops/tests/bats/fixtures/docker-compose.fixture2.yml
=> chore: Unpinned Chrome driver and enabled w3c mode for driver.

scripts/drevops/build.sh, scripts/drevops/tests/bats/_helper_workflow.bash
=> feat: Added build time.

scripts/drevops/installer/composer.json, scripts/drevops/installer/composer.lock, scripts/drevops/installer/install.php, scripts/drevops/installer/tests/functional/FunctionalTestBase.php, scripts/drevops/installer/tests/functional/MainTest.php, scripts/drevops/installer/tests/traits/TestHelperTrait.php, scripts/drevops/installer/tests/unit/CopyRecursiveTest.php, scripts/drevops/installer/tests/unit/DotEnvTest.php, scripts/drevops/installer/tests/unit/HelpersTest.php, scripts/drevops/installer/tests/unit/TokenTest.php, scripts/drevops/installer/tests/unit/UnitTestBase.php
https://your-site.atlassian.net/browse/YSCODE-<NUMBER>
1.
=> chore: Added scaffold for functional tests for installer and upgraded to PHPUnit 10.

scripts/drevops/tests/unit/DrupalSettingsTest.php, web/sites/default/settings.php
https://your-site.atlassian.net/browse/YSCODE-<NUMBER>
1.
=> bug: Do not run automated cron in CI.

.docker/cli.dockerfile, .env.local.example, docker-compose.yml, scripts/drevops/build.sh, scripts/drevops/docs/variables.md, scripts/drevops/github-labels.sh, scripts/drevops/tests/bats/_helper.bash, scripts/drevops/tests/bats/_helper_workflow.bash, scripts/drevops/tests/bats/fixtures/docker-compose.fixture.yml, scripts/drevops/tests/bats/fixtures/docker-compose.fixture2.yml, scripts/drevops/tests/bats/workflow0.bats
=> feat: Added support for composer packages authentication using GITHUB_TOKEN env variable.

docker-compose.yml, scripts/drevops/tests/bats/fixtures/docker-compose.fixture.yml, scripts/drevops/tests/bats/fixtures/docker-compose.fixture2.yml
=> bug: Fixed local emails not being sent to Mailhog.

.lagoon.yml, scripts/drevops/tests/bats/install_integrations.bats
=> Simplified Lagoon config.

.env, composer.json, docker-compose.yml, scripts/drevops/docs/usage/variables.md, scripts/drevops/tests/bats/fixtures/docker-compose.env.json, scripts/drevops/tests/bats/fixtures/docker-compose.env_mod.json, scripts/drevops/tests/bats/fixtures/docker-compose.noenv.json, tests/behat/bootstrap/FeatureContext.php, tests/behat/features/clamav.feature, tests/phpunit/DrupalSettingsTest.php, web/modules/custom/ys_core/ys_core.deploy.php, web/modules/custom/ys_core/ys_core.info.yml, web/sites/default/includes/settings.clamav.php
=> feat: Added ClamAV support.

.circleci/config.yml, scripts/drevops/docs/.ahoy.yml, scripts/drevops/docs/.utils/release.sh
=> bug: Fixed docs publishing.

.env, composer.json, phpstan.neon, scripts/drevops/build.sh, scripts/drevops/docs/usage/variables.md, scripts/drevops/lint-be.sh, scripts/drevops/tests/bats/_helper.bash, scripts/drevops/tests/bats/_helper_deployment.bash
=> feat: Added support for PHPStan.

.circleci/config.yml
=> bug: Fixed  DREVOPS_DB_DOCKER_IMAGE_BASE not being pinned to a version.

docker-compose.yml, scripts/drevops/doctor.sh
=> chore: Added back mounting volues from pygmy.

.env, scripts/drevops/docs/usage/variables.md, scripts/drevops/lint-be.sh, scripts/drevops/lint-fe.sh, scripts/drevops/lint.sh, scripts/drevops/test-bdd.sh, scripts/drevops/test-functional.sh, scripts/drevops/test-kernel.sh, scripts/drevops/test-unit.sh, scripts/drevops/test.sh, scripts/drevops/tests/bats/_helper_workflow.bash, scripts/drevops/tests/bats/workflow.install.bats
=> chore: Updated front-end linter bypass logic and messages.

.env, composer.json, scripts/drevops/docs/introduction/features.md, scripts/drevops/docs/usage/variables.md, scripts/drevops/lint-fe.sh, scripts/drevops/tests/bats/_helper_workflow.bash
=> feat: Added support for Twigcs.

scripts/drevops/deploy.sh, scripts/drevops/docs/usage/deploy.md
=> docs: Added deployment docs.

.docker/cli.dockerfile, .docker/nginx-drupal.dockerfile, .docker/php.dockerfile, .env, docker-compose.yml, scripts/drevops/docs/content/tools/variables.md, scripts/drevops/tests/bats/_helper_workflow.bash, scripts/drevops/tests/bats/fixtures/docker-compose.env.json, scripts/drevops/tests/bats/fixtures/docker-compose.env_mod.json, scripts/drevops/tests/bats/fixtures/docker-compose.noenv.json, scripts/drevops/tests/bats/workflow.install.bats
=> [#939] Added support for setting timezone in containers.

README.md, composer.json, scripts/drevops/installer/install.php, scripts/drevops/tests/bats/_helper.bash, scripts/drevops/tests/bats/env.bats
=> Fixed latest version discovery in installer.

.docker/cli.dockerfile, .docker/mariadb.dockerfile, scripts/drevops/tests/lint.dockerfiles.sh
=> Fixed variables format in Dockerfiles and added variables linter to the script.

.circleci/config.yml, renovate.json
=> Added support for Dockerfile updates in Renovate configurations.

.drevops/docs/content/tools/variables.md, .env, scripts/drevops/build.sh
=> Enabled verbose output for Docker and composer.

.circleci/config.yml, .drevops/docs/.utils/variables/extra/ci.variables.sh, .drevops/docs/content/tools/variables.md, .drevops/docs/content/workflow/test.md, .drevops/tests/test.workflow.sh
=> Separated tooling runs in CI and updated variables.

.drevops/docs/content/tools/variables.md, .env
=> Added DREVOPS_NOTIFY_EMAIL_FROM to .env.

.env
=> Removed buildkit disabling.

.docker/cli.dockerfile, .docker/mariadb.dockerfile, .docker/nginx-drupal.dockerfile, .docker/php.dockerfile, .docker/solr.dockerfile, .drevops/tests/bats/fixtures/docker-compose.env.json, .drevops/tests/bats/fixtures/docker-compose.env_mod.json, .drevops/tests/bats/fixtures/docker-compose.noenv.json, docker-compose.yml
https://github.com/uselagoon/lagoon-images/releases/tag/23.10.0
=> Update Docker image updates to v23.10.0

.drevops/docs/.utils/variables/extra/.env.local.default.variables.sh, .drevops/docs/content/workflows/variables.md, .env.local.default, docker-compose.yml
=> Allow to provide custom DREVOPS_LOCALDEV_URL.

composer.json
=> Updated stage_file_proxy to v2.

.ahoy.yml, .docker/cli.dockerfile, scripts/drevops/build.sh
=> moved files creation into container

.docker/cli.dockerfile, .docker/php.dockerfile, .drevops/devtool/composer.json, .drevops/devtool/src/Scaffold/ComposerJsonScaffoldComponent.php, .drevops/devtool/tests/phpunit/Fixtures/root_dir/.docker/cli.dockerfile, .drevops/docs/content/drupal/composer.md, .drevops/installer/composer.json, .drevops/tests/composer.lock, composer.json
=> Updated to PHP 8.2.

.drevops/tests/bats/_helper.workflow.bash
=> Added tests for Redis requirements reporting.

.circleci/config.yml
=> Replaced Codecov orb with a binary uploader.

.circleci/config.yml, .drevops/tests/bats/_helper.bash, tests/phpunit/CircleCiConfigTest.php
=> [#1127] Updated CI job names to consists of hyphens only.

.drevops/tests/bats/_helper.bash, .github/PULL_REQUEST_TEMPLATE.md, .github/release-drafter.yml, .github/workflows/assign-author.yml, .github/workflows/draft-release-notes.yml, .github/workflows/label-merge-conflict.yml
https://github.com/AlexSkrypnyk/scaffold
=> Updated GitHub actions to the latest scaffold.

.docker/cli.dockerfile, .docker/nginx-drupal.dockerfile, .docker/php.dockerfile
=> [#1184] Unpinned APK packaged versions.

.env
=> [#1187] Set DRUPAL_PROFILE to 'standard'.

.circleci/config.yml, .drevops/tests/bats/circleci.bats, .drevops/tests/test.deployment.sh, .drevops/tests/test.workflow.sh, .github/workflows/drevops-test-common.yml, README.md
=> [#1197] Moved DrevOps tests to GHA.

.drevops/docs/content/introduction/features.md, .drevops/tests/bats/_helper.bash, README.dist.md, README.md
=> [#1225] Moved consumer part of README to own file.

scripts/composer/ScriptHandler.php
=> [#944] Updated ScriptHandler to follow the latest version from drupal-project.

.scaffold/docs/content/workflows/variables.mdx, .scaffold/tests/bats/deployment1.bats, scripts/drevops/deploy-lagoon.sh, scripts/drevops/task-custom-lagoon.sh
=> [#1248] Simplified LagoonCLI variables.

scripts/custom/provision-10-example.sh, web/modules/custom/ys_core/ys_core.info.yml
=> [#1261] Removed the dependencies on the optional modules from the core module.

scripts/drevops/deploy-docker.sh, scripts/drevops/deploy-lagoon.sh, scripts/drevops/deploy-webhook.sh, scripts/drevops/doctor.sh, scripts/drevops/download-db-acquia.sh, scripts/drevops/download-db-curl.sh, scripts/drevops/download-db-docker-registry.sh, scripts/drevops/download-db-ftp.sh, scripts/drevops/download-db-lagoon.sh, scripts/drevops/download-db.sh, scripts/drevops/export-db-docker.sh, scripts/drevops/export-db.sh, scripts/drevops/github-labels.sh, scripts/drevops/login-docker.sh, scripts/drevops/mirror-code.sh, scripts/drevops/notify-github.sh, scripts/drevops/notify-jira.sh, scripts/drevops/notify-newrelic.sh, scripts/drevops/reset.sh, scripts/drevops/setup-ssh.sh, scripts/drevops/task-copy-db-acquia.sh, scripts/drevops/task-copy-files-acquia.sh, scripts/drevops/task-custom-lagoon.sh, scripts/drevops/task-purge-cache-acquia.sh, scripts/drevops/update-scaffold.sh
=> [#768] Added checking for bin existence in scripts.

.scaffold/docs/docusaurus.config.js
=> [#1280] Updated docs: Edit this page on GitHub links to the correct URL

.ahoy.yml, .circleci/config.yml, .env, .scaffold/docs/.utils/variables/extra/.env.variables.sh, .scaffold/docs/content/workflows/variables.mdx, .scaffold/tests/bats/_helper.bash, .scaffold/tests/bats/docker-compose.bats, .scaffold/tests/bats/install.initial.bats, .scaffold/tests/bats/workflow.storage.curl.bats, .scaffold/tests/bats/workflow.storage.image.bats, .scaffold/tests/bats/workflow.storage.image_cached.bats, docker-compose.yml, scripts/drevops/download-db-docker-registry.sh, scripts/drevops/download-db.sh, scripts/drevops/export-db.sh, scripts/drevops/info.sh, scripts/drevops/provision.sh
=> [#1293] Simplified `DREVOPS_DB_DOCKER_IMAGE` to `DREVOPS_DB_IMAGE`.

.docker/mariadb.dockerfile, .scaffold/tests/bats/fixtures/docker-compose.env.json, .scaffold/tests/bats/fixtures/docker-compose.env_local.json, .scaffold/tests/bats/fixtures/docker-compose.noenv.json, docker-compose.yml
=> [#1297] Updated to `mariadb-10.11-drupal` image.

.scaffold/tests/bats/workflow.utilities.bats
=> [#1305] Added tests for renovate config.

.github/workflows/close-pull-request.yml, .github/workflows/scaffold-release-docs.yml, .github/workflows/scaffold-test-common.yml, .scaffold/tests/.yamllint-for-gha.yml
=> [#1307] Added linting for GHAs.

.scaffold/docs/content/workflows/variables.mdx, .scaffold/tests/bats/provision.bats, scripts/drevops/provision.sh
=> [#1315] Added Drupal config dir auto-discovery during provisioning.

.github/workflows/renovate.yml
This is a feature-parity functionality for GHA and CircleCI.
=> Added Renovate self-hosted GHA.

composer.json
See discussion https://github.com/drupal-composer/drupal-project/issues/379
=> Removed `vlucas/phpdotenv`.

renovate.json
https://docs.renovatebot.com/configuration-options/#configmigration
=> Added Renovate config migration.

.scaffold/tests/bats/docker-compose.bats, .scaffold/tests/bats/fixtures/docker-compose.env.json, .scaffold/tests/bats/fixtures/docker-compose.env_local.json, .scaffold/tests/bats/fixtures/docker-compose.env_mod.json, .scaffold/tests/bats/fixtures/docker-compose.noenv.json, docker-compose.yml
=> [#1371] Removed `SSMTP_MAILHUB` override.

.ahoy.yml
=> [#1399] Added `ahoy fetch-db` as an alias to `ahoy download-db`.

.vortex/docs/content/drupal/settings.mdx, tests/phpunit/Drupal/EnvironmentSettingsTest.php, tests/phpunit/Drupal/SettingsTestCase.php, tests/phpunit/Drupal/SwitchableSettingsTest.php, web/sites/default/includes/modules/settings.config_split.php, web/sites/default/includes/modules/settings.environment_indicator.php, web/sites/default/includes/providers/settings.acquia.php, web/sites/default/includes/providers/settings.lagoon.php, web/sites/default/settings.php
=> [#1422] Renamed `ENVIRONMENT_TEST` to `ENVIRONMENT_STAGE`.

web/sites/default/default.settings.local.php, web/sites/default/settings.php
=> [#1419] Moved `services.local.php` inclusion into `settings.local.php`.

.twig-cs-fixer.php, .vortex/docs/content/tools/twig-cs-fixer.mdx
=> [#1455] Updated TwigCSFixer rules

behat.yml, composer.json
See changes: https://github.com/drevops/behat-screenshot/compare/9b542ff...2.0.0
Release notes: https://github.com/drevops/behat-screenshot/releases/tag/2.0.0
=> Updated to Behat Screenshot v2.

.circleci/config.yml, .github/workflows/build-test-deploy.yml
This is to allow fast fail on the inconsistent composer.lock
=> Moved composer config validation to run on host in CI.

.circleci/config.yml, .github/workflows/build-test-deploy.yml
=> [#1517] Fixed DB cache not being reset in GHA on scheduled run.

.github/workflows/build-test-deploy.yml
=> [#1518] Do not run deploy on `deps/*` branches.

.github/workflows/build-test-deploy.yml
=> [#1522] Moved uploading of exported codebase as artifact to a later stage in GHA.

.ahoy.yml, .circleci/config.yml, .env, .github/workflows/build-test-deploy.yml, .vortex/docs/.utils/variables/extra/docker-compose.variables.sh, .vortex/docs/content/contributing/maintenance/scripts.mdx, .vortex/docs/content/tools/docker.mdx, .vortex/docs/content/workflows/variables.mdx, .vortex/installer/src/Traits/PromptsTrait.php, .vortex/tests/bats/_helper.workflow.bash, .vortex/tests/bats/docker-compose.bats, .vortex/tests/bats/install.existing.bats, .vortex/tests/bats/install.parameters.bats, docker-compose.yml, scripts/vortex/download-db-lagoon.sh, scripts/vortex/info.sh, scripts/vortex/provision.sh, scripts/vortex/reset.sh
=> [#1525] Simplified `VORTEX_WEBROOT` and `VORTEX_TZ` variables.

.vortex/installer/src/Command/InstallCommand.php
=> Updated installer header to be more subtle.

.circleci/config.yml, .github/workflows/build-test-deploy.yml, .github/workflows/vortex-test-common.yml, .vortex/installer/tests/Fixtures/install/_baseline/.github/workflows/build-test-deploy.yml, .vortex/installer/tests/Fixtures/install/ciprovider_circleci/.circleci/config.yml, .vortex/installer/tests/Fixtures/install/deploy_type_all_circleci/.circleci/config.yml, .vortex/installer/tests/Fixtures/install/deploy_type_none_circleci/.circleci/config.yml, .vortex/installer/tests/Fixtures/install/deps_updates_provider_ci_circleci/.circleci/config.yml, .vortex/installer/tests/Fixtures/install/provision_profile/.github/workflows/build-test-deploy.yml
This will help to avoid rate limits during the consumer site tests and during Vortex self-tests.
=> Fixed docker login in build and self-tests to take place before any docker operations.
