drevops/vortex

.circleci/config.yml
.dev/DEPLOYMENT.template.md

This is to remove confusion between `release/*` branches in SRC and DST repos.

Updated deployment branch.

---

.gitignore
composer.json
composer.lock
tests/bats/install_existing.bats
tests/bats/test_helper_drupaldev.bash

Fixes an issue where scaffold files (`docroot/index.php` etc) are not explicitly whitelisted in `.gitignore` when the stack is installed.

[8.x] Fixed whitelisting of scaffold files.

---

composer.json

Example
"npm-asset/select2": "^4.0"
closes #606

[#606] Added support for NPM assets packages for libraries.

---

.ahoy.yml
scripts/drevops/tests/bats/_helper_drevops_workflow.bash
scripts/drevops/tests/bats/workflow0.bats

I have added  `ahoy composer` many times without the `ahoy cli composer`, this PR adds composer as a first class ahoy command.
1. Added `composer` command.
2. Added tests to ensure it is running correctly.

[9.x] Added composer cmd to ahoy.

---

scripts/drevops/docs/mkdocs.yml
scripts/drevops/docs/test.md
scripts/drevops/installer/install.php
scripts/drevops/test.sh
scripts/drevops/tests/.aspell.en.pws
scripts/drevops/tests/bats/_helper.bash
scripts/drevops/tests/bats/_helper_workflow.bash
scripts/drevops/tests/bats/install_existing.bats
scripts/drevops/tests/bats/install_initial.bats
web/modules/custom/ys_core/tests/src/Functional/ExampleTest.php
web/modules/custom/ys_core/tests/src/Functional/YsCoreFunctionalTestBase.php
web/modules/custom/ys_core/tests/src/Kernel/ExampleTest.php
web/modules/custom/ys_core/tests/src/Kernel/YsCoreKernelTestBase.php
web/modules/custom/ys_core/tests/src/Unit/ExampleTest.php
web/modules/custom/ys_core/tests/src/Unit/YsCoreUnitTestBase.php
web/themes/custom/your_site_theme/tests/src/Functional/ExampleTest.php
web/themes/custom/your_site_theme/tests/src/Functional/YourSiteThemeFunctionalTestBase.php
web/themes/custom/your_site_theme/tests/src/Kernel/ExampleTest.php
web/themes/custom/your_site_theme/tests/src/Kernel/YourSiteThemeKernelTestBase.php
web/themes/custom/your_site_theme/tests/src/Traits/YourSiteThemeTestHelperTrait.php
web/themes/custom/your_site_theme/tests/src/Unit/ExampleTest.php
web/themes/custom/your_site_theme/tests/src/Unit/YourSiteThemeUnitTestBase.php

closes #741 
- Added support for tests in scripts
- Added support for tests in themes
- Tests now needs to be correctly tagged with `site:<suite>` (`site:unit', `site:kernel`, `site:functional`) instead of having a `<Suit>Test.php` suffix
- Added documentation about running tests

feat: Added support for tags in tests.

---

.circleci/config.yml
scripts/drevops/docs/.ahoy.yml
scripts/drevops/docs/.utils/Dockerfile
scripts/drevops/docs/.utils/release.sh
scripts/drevops/docs/maintenance/updating-documentation.md
scripts/drevops/docs/mkdocs.yml

Docs are published to:
- `dev` when merged to `main`
- `{branch-name-hyphenated}` when source branch contains `docs` substring
- `{version}` on release; `latest` is symlinked to the release as well.

chore: Added multi-version docs publishing.

---

drush/drushrc.php
scripts/drevops/docs/maintenance/authoring-scripts.md
scripts/drevops/download-db-lagoon.sh
scripts/drevops/drupal-install-site.sh
scripts/drevops/drupal-login.sh
scripts/drevops/drupal-logout.sh
scripts/drevops/drupal-sanitize-db.sh
scripts/drevops/export-db-file.sh
scripts/drevops/tests/bats/drupal_install_site.bats

- Updated drush commands to use the full notation.
- Updated installation summary:
```
[INFO] Started site installation.
App dir                      : /app
Web root dir                 : web
Site name                    : YOURSITE
Site email                   : webmaster@your-site-url.example
Profile                      : your_site_profile
Private files directory      : /app/web/sites/default/files/private
Config path                  : /app/config/default
DB dump file path            : /app/.data/db.sql (present)
Drush binary                 : /app/vendor/bin/drush
Drush version                : Drush Commandline Tool 11.5.1
Drupal core version          : 10.0.9
Install from profile         : No
Overwrite existing DB        : No
Skip sanitization            : No
Use maintenance mode …
```

chore: Updated scripts to use full drush commands and improved site install information.

---

.circleci/config.yml
.drevops/docs/.utils/.aspell.en.pws
.drevops/docs/.utils/Dockerfile
.drevops/docs/content/tools/hadolint.md
.drevops/docs/mkdocs.yml

[#1035] Added Hadolint to CI for consumer sites.

---

.circleci/config.yml

See https://discuss.circleci.com/t/remote-docker-image-deprecations-and-eol-for-2024/50176

Updated CI to use the default Docker image.

---

.lagoon.yml

[#1175] Show DrevOps variables in Lagoon only when $DREVOPS_DEBUG is set.

---

phpmd.xml
web/modules/custom/ys_core/ys_core.deploy.php

[#1093] Exclude phpmd for deploy, post-update & install file.

---

composer.json

This version unblocks updates to the newer versions of Mink.

Updated behat-steps to use the ^2.2 vesion.

---

.drevops/tests/bats/deployment1.bats
scripts/drevops/deploy-lagoon.sh

closes #952
1. Updated to lagoon update variable rather than add and delete.
2. Updated tests.

[#952] Updated Lagoon deployment script to use `variable update`.

---

.scaffold/tests/bats/deployment1.bats
scripts/drevops/deploy-lagoon.sh
scripts/drevops/task-custom-lagoon.sh

1. Added lagoon function wrapper to bash cmds.

[#942] Added lagoon wrapper to cmds.

---

.scaffold/tests/bats/_helper.deployment.bash
.scaffold/tests/bats/deploy-docker.bats
.scaffold/tests/bats/deployment-webhook.bats
.scaffold/tests/bats/login-docker.bats

closes #736
1. Added tests for webhook, docker login and docker deployment scripts

[#736] Added tests for `webhook` and `docker` deployment.

---

.circleci/config.yml

1. It seems the regex for filter branches is not valid.

Fixed regex in deployment branches filter

---

.github/workflows/close-pull-request.yml
.scaffold/tests/bats/_helper.bash

[#1259] Renamed `dispatch-webhook-lagoon.yml` to `close-pull-request.yml`.

---

.ahoy.yml
.circleci/config.yml
.scaffold/tests/bats/_helper.bash
.scaffold/tests/bats/_helper.deployment.bash
.scaffold/tests/bats/_helper.workflow.bash
.scaffold/tests/bats/workflow.smoke.bats

[#1279] Remove DB copy from `ahoy provision`.

---

phpunit.xml

[#1284] Excluded test files from the coverage report.

---

.docker/cli.dockerfile
.scaffold/tests/bats/fixtures/docker-compose.env.json
.scaffold/tests/bats/fixtures/docker-compose.env_local.json
.scaffold/tests/bats/fixtures/docker-compose.env_mod.json
.scaffold/tests/bats/fixtures/docker-compose.noenv.json
docker-compose.yml
tests/phpunit/Drupal/EnvironmentSettingsTest.php
tests/phpunit/Drupal/SettingsTestCase.php
web/sites/default/settings.php

[#1328] Added support for custom configuration location via `DRUPAL_CONFIG_PATH`.

---

.lagoon.yml
.scaffold/.ahoy.yml
.scaffold/docs/content/workflows/variables.mdx
.scaffold/tests/bats/notify.bats
hooks/library/notify-deployment.sh
scripts/drevops/notify-github.sh

Closes #1065
The root cause was related to the fact that a Git ref was used instead of a branch name for PRs.
From https://docs.github.com/en/rest/deployments/deployments?apiVersion=2022-11-28
> `ref` string
The name of the ref. This can be a branch, tag, or SHA.
The script was using `DREVOPS_NOTIFY_REF` instead of `DREVOPS_NOTIFY_BRANCH` for PRs. This PR fixes that.
It also adds 2 more changes:
1. More verbose messages on failures + tests.
2. **Failed notifications are now NOT blocking deployments.** This is to allow to deploy into hosting without waiting for the CI to pass (setting the deployment environment status for the PR without all checks passed will fail).
With the now additionally expanded messages, this should provide enough information

[#1065] Fixed failing GitHub notifications.

---

scripts/drevops/deploy-lagoon.sh

On-behalf-of: @salsadigitalauorg <sonny.kieu@salsa.digital>
1. Fixed issue with Lagoon CLI 0.30
```
+ command lagoon --force --skip-update-check -i /root/.ssh/id_rsa_xxx -l amazeeio -p xxx deploy pullrequest -n 1219 --baseBranchName develop -R origin/develop -H feature/XXX -M 5cbf1699887c5cf3092b3ef3e61c344fa51aeec9 -t pr-1219
Error: unknown flag: --baseBranchName
Usage:
lagoon deploy pullrequest [flags]
Aliases:
pullrequest, r
Flags:
-N, --base-branch-name string   Pullrequest base branch name
-R, --base-branch-ref string    Pullrequest base branch reference hash
--buildvar stringArray      Add one or more build variables to deployment (--buildvar KEY1=VALUE1 [--buildvar KEY2=VALUE2])
-H, --head-branch-name string   Pullrequest head branch name
-M, --head-branch-ref string    Pullrequest …
```

Fixed to use correct deploy PR flag with Lagoon CLI 0.30.

---

.scaffold/tests/bats/_helper.bash
README.dist.md

[#1370] Added footer note to the consumer `README.md`.

---

.github/workflows/draft-release-notes.yml
docs/releasing.md

[#1212] Added support for `CalVer` scheme when generating release notes.

---

.circleci/config.yml
tests/phpunit/Drupal/SettingsTestCase.php

CircleCI does not support variables evaluation in `environment`. Have to go back to YAML aliases.

Fixed self-hosted Renovate configuration in CI.

---

.twig-cs-fixer.php
composer.json
web/modules/custom/ys_core/tests/src/Traits/ReflectionTrait.php

Without this, some of the rules are skipped.
https://github.com/VincentLanglet/Twig-CS-Fixer/blob/main/docs/configuration.md#non-fixable-rules

Added reporting of non-fixable rule to TwigCS Fixer.

---

composer.json
tests/phpunit/Drupal/EnvironmentSettingsTest.php
web/sites/default/includes/modules/settings.seckit.php

[#1421] Added SecKit module.

---

.circleci/config.yml

[#1433] Updated deployment keys for CircleCI.

---

.circleci/config.yml
.docker/cli.dockerfile
.github/workflows/build-test-deploy.yml
.github/workflows/vortex-test-installer.yml
.vortex/docs/content/tools/phpunit.mdx

[#1453] Replaced Xdebug with PCOV for coverage.

---

.github/workflows/build-test-deploy.yml

Code artifact created during `build` and passed to `deploy` was stored for a full retention period as other artifacts, which filled in the storage:
```
Error: Failed to CreateArtifact: Artifact storage quota has been hit. Unable to upload any new artifacts. Usage is recalculated every 6-12 hours.
More info on storage limits: https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#calculating-minute-and-storage-spending
```
This artifact is only required for a duration of the build, so the storage period should be only 1 day.

Fixed code artifact in GHA being stored unnecessary long leading to hitting storage rate limits.
